### ISSUE TITLE
TypeError: Plain typing.NoReturn is not valid as type argument

### ISSUE THREAD

**Issue by rohanpm** [rohanpm/pidiff#82]
pidiff used on iiblib project & python 3.7 generated this error - why?

```
pidiff run-test: commands[0] | pidiff iiblib .
Traceback (most recent call last):
  File "/home/travis/build/release-engineering/iiblib/.tox/pidiff/bin/pidiff", line 6, in <module>
    from pidiff._impl.command import main
  File "/home/travis/build/release-engineering/iiblib/.tox/pidiff/lib/python3.7/site-packages/pidiff/_impl/command.py", line 256, in <module>
    def detect_module(env1, pkg1, env2, pkg2) -> Union[str, NoReturn]:
  File "/opt/python/3.7.1/lib/python3.7/typing.py", line 251, in inner
    return func(*args, **kwds)
  File "/opt/python/3.7.1/lib/python3.7/typing.py", line 348, in __getitem__
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "/opt/python/3.7.1/lib/python3.7/typing.py", line 348, in <genexpr>
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "/opt/python/3.7.1/lib/python3.7/typing.py", line 135, in _type_check
    raise TypeError(f"Plain {arg} is not valid as type argument")
TypeError: Plain typing.NoReturn is not valid as type argument
ERROR: InvocationError for command /home/travis/build/release-engineering/iiblib/.tox/pidiff/bin/pidiff iiblib . (exited with code 1)
```

**Comment by rohanpm** [comment]
This was a bug in python 3.7.1: https://bugs.python.org/issue34921
